### ISSUE TITLE
Can not read static binaries

### ISSUE THREAD

**Issue by archi** [SNSystems/DIVA#1] opened 2017-03-29 11:33 UTC
I just played around with diva, and seems like it fails to open static binaries?

Output:

> ERR_INVALID_DWARF: Failed to read DWARF from 'clang-static.elf'

The binaries are built on OpenSUSE Leap 42.2 with gcc 4.8.5 and clang 3.8, flags "-g -static":
I also tried our CompCert C Compiler (recent, internal build), and diva can read both statically and dynamically linked executables.

The file utility outputs this information for the failing files:

> clang-static.elf:    ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.0.0, BuildID[sha1]=..., not stripped
> gcc-static.elf:      ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.0.0, BuildID[sha1]=..., not stripped

These work:
> gcc.elf:             ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.0.0, BuildID[sha1]=..., not stripped
> clang.elf:           ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.0.0, BuildID[sha1]=..., not stripped
> compcert.elf:        ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
> compcert-static.elf: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

Tested both on Linux with wine and in a Windows VM.

**Comment by FreakyDug** [comment] 2017-03-30 09:59
Hi, thanks for taking a look at Diva!

I haven't been able to reproduce the problem you describe using clang or gcc with ld or Gold. Could you send us an example elf and/or the source you built?

**Comment by archi** [comment] 2017-03-30 10:44
After the talk I was quite interested in it :)

I attached source (hello.c) and all the executables I built.

gcc.elf is the non-static executable, and gcc.elf.log the compiler output (run with --verbose). gcc-static.elf is the static one, and the log is in gcc-static.elf.log.
Same for clang. Both gcc and clang are the versions shipped with OpenSUSE, so these are no special, magical builds ;)

I dumped gcc/clang --version into the respective files (gcc/clang-version.txt).

For compcert, I didn't create log files, but it's relying on a custom built gcc toolchain for linking (x86_64-unknown-linux-uclibc-ld).

[diva-test.tar.gz](https://github.com/SNSystems/DIVA/files/881832/diva-test.tar.gz)

**Comment by p23power** [comment] 2017-03-30 13:07
Hi archi,

Thanks for the details.  We can now reproduce and are looking into it. 

FYI: Just uploaded the Linux binaries for v0.3 (no functional changes compared to the one you are already using)

**Comment by p23power** [comment] 2017-03-31 15:17
Hi archi,
A v0.3.1 release has been uploaded which should fix your issue.  Please can you confirm the fix.
Thanks

**Comment by archi** [comment] 2017-03-31 16:08
Hi p23power, yes, it works :) Thanks!

**Comment by dtzWill** [comment] 2017-04-04 12:12
(looks like this can be closed? :smile:)

**Comment by p23power** [comment] 2017-04-21 10:36
Closing

**Closed by p23power** 2017-04-21 10:36 UTC
